name: publish-slides
concurrency: publish-slides

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: mkdir -p slides

      - name: Copy images directory (if exists)
        run: if [[ -d img ]]; then cp -R img slides/img; fi

      - name: Marp Build - HTML
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: slides.md -o slides/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build - PDF
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: slides.md --allow-local-files -o slides/GettingStartedWithReact.pdf
        env:
          MARP_USER: root:root

      - name: Marp Build - PPTX
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: slides.md --allow-local-files -o slides/GettingStartedWithReact.pptx
        env:
          MARP_USER: root:root

      - name: Publish slides artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./slides"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
